# use command
# configtxgen -profile TwoOrgsOrdererGenesis -channelID swordartonline-sys -outputBlock ./channel-artifacts/genesis.block
# configtxgen -profile TwoOrgsChannel -outputCreateChannelTx ./channel-artifacts/swordartonline.tx -channelID swordartonline
# configtxgen -profile TwoOrgsChannel -outputAnchorPeersUpdate ./channel-artifacts/KiritoAnchors.tx -channelID swordartonline -asOrg Kirito
# configtxgen -profile TwoOrgsChannel -outputAnchorPeersUpdate ./channel-artifacts/AsunaAnchors.tx -channelID swordartonline -asOrg Asuna
---
Organizations:
  - &AkihikoOrg
    Name: Akihiko
    ID: Akihiko
    MSPDir: crypto-config/ordererOrganizations/akihiko.moe/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Akihiko.member')"
      Writers:
        Type: Signature
        Rule: "OR('Akihiko.member')"
      Admins:
        Type: Signature
        Rule: "OR('Akihiko.admin')"

  - &KiritoOrg
    Name: Kirito
    ID: Kirito
    MSPDir: crypto-config/peerOrganizations/kirito.moe/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Kirito.member', 'Kirito.peer', 'Kirito.client')"
      Writers:
        Type: Signature
        Rule: "OR('Kirito.member', 'Kirito.client')"
      Admins:
        Type: Signature
        Rule: "OR('Kirito.admin')"
    AnchorPeers:
      - Host: peer0.kirito.svc.cluster.local
        Port: 7051

  - &AsunaOrg
    Name: Asuna
    ID: Asuna
    MSPDir: crypto-config/peerOrganizations/asuna.moe/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Asuna.member', 'Asuna.peer', 'Asuna.client')"
      Writers:
        Type: Signature
        Rule: "OR('Asuna.member', 'Asuna.client')"
      Admins:
        Type: Signature
        Rule: "OR('Asuna.admin')"
    AnchorPeers:
      - Host: peer0.asuna.svc.cluster.local
        Port: 7051


Capabilities:
  Channel: &ChannelCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: false
    V1_1: false

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

Orderer: &OrdererDefaults
  OrdererType: kafka
  Addresses:
    - orderer.akihiko.svc.cluster.local:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99MB
    PreferredMaxBytes: 512KB
  Kafka:
    Brokers:
      - kafka-svc.kafka.svc.cluster.local:9092

  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Channel: &ChannelDefault
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefault
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *AkihikoOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *KiritoOrg
          - *AsunaOrg

  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *KiritoOrg
        - *AsunaOrg
      Capabilities:
        <<: *ApplicationCapabilities