---
OrdererOrgs:
  - Name: Aincrad
    Domain: aincrad.moe
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Kirito
    Domain: kirito.moe
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Asuna
    Domain: asuna.moe
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1