NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.asuna.moe-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.asuna.moe-cert.pem
    OrganizationalUnitIdentifier: peer
